import { test, type TestContext } from 'node:test';
import assert from 'node:assert/strict';
import Stripe from 'stripe';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store } from '../lib/store';
import { Commerce } from '../lib/service';
import { StripePaymentProvider } from '../lib/payments';
import { queueVerifiedStripeEvent } from '../lib/webhooks';
import { OperationUnknown, type Run, type WebhookReceipt } from '../lib/types';
function setup(store = new Store(':memory:')) {
  const c = new Commerce(store, 'stripe'); let run = c.create('buyer', 'HK$1800 headphones official warranty');
  run = c.quote(run.id, 'buyer', 'merchant_a', 'acct_fixture'); c.approve(run.id, 'buyer', run.mandate!.id, run.mandate!.hash); c.commit(run.id, 'buyer');
  c.change(run.id, r => { r.sessionId = 'cs_fixture'; r.stage = 'WAIT_AUTH'; r.status = 'WAITING_PAYMENT'; r.providerState = 'open'; }, 'LOCAL webhook fixture');
  return { store, c, run: c.get(run.id) };
}
function event(run: Run, id = 'evt_fixture', type = 'payment_intent.amount_capturable_updated', objectId = 'pi_fixture') {
  return { id, type, created: Math.floor(Date.now() / 1000), livemode: false, data: { object: { id: objectId, object: 'payment_intent', livemode: false, amount: 174900, currency: 'hkd', status: 'requires_capture', metadata: { run_id: run.id, mandate_id: run.mandate!.id, mandate_hash: run.mandate!.hash, payee_id: run.mandate!.offer.payee } } } } as unknown as Stripe.Event;
}
function provider(t: TestContext) {
  const old = process.env.STRIPE_SECRET_KEY; process.env.STRIPE_SECRET_KEY = 'sk_test_local_fixture'; t.after(() => { if (old === undefined) delete process.env.STRIPE_SECRET_KEY; else process.env.STRIPE_SECRET_KEY = old; });
  let status: 'requires_capture' | 'succeeded' | 'canceled' = 'requires_capture', captures = 0;
  const payment = () => ({ id: 'pi_fixture', mode: 'stripe' as const, amountMinor: 174900, currency: 'hkd', status, captureBefore: new Date(Date.now() + 86400000).toISOString() });
  t.mock.method(StripePaymentProvider.prototype, 'retrieve', async () => payment());
  t.mock.method(StripePaymentProvider.prototype, 'capture', async () => { captures++; status = 'succeeded'; return payment(); });
  t.mock.method(StripePaymentProvider.prototype, 'cancel', async () => { status = 'canceled'; return payment(); });
  return { captures: () => captures, settle: () => { status = 'succeeded'; } };
}
test('SDK signature fixture verifies original raw bytes and rejects wrong secret/mutated body (LOCAL FIXTURE)', () => { const stripe = new Stripe('sk_test_fixture'), secret = 'whsec_local_fixture'; const raw = JSON.stringify({ id: 'evt_sig_fixture', type: 'payment_intent.succeeded', data: { object: {} } }); const header = stripe.webhooks.generateTestHeaderString({ payload: raw, secret }); assert.equal(stripe.webhooks.constructEvent(raw, header, secret).id, 'evt_sig_fixture'); assert.throws(() => stripe.webhooks.constructEvent(raw + ' ', header, secret)); assert.throws(() => stripe.webhooks.constructEvent(raw, header, 'whsec_wrong_fixture')); });
test('valid notification durably queues before acknowledgment; duplicate creates no extra event/job/payment', () => { const { store, run } = setup(); const before = store.events(run.id).length; const accepted = queueVerifiedStripeEvent(store, event(run)); assert.ok('queued' in accepted && accepted.queued); assert.equal(store.get<WebhookReceipt>('stripe_webhook', 'evt_fixture')?.status, 'PENDING'); const duplicate = queueVerifiedStripeEvent(store, event(run)); assert.ok('duplicate' in duplicate && duplicate.duplicate); assert.equal(store.events(run.id).length, before + 1); assert.equal(store.db.prepare('SELECT COUNT(*) n FROM jobs').get()!.n, 1); assert.equal(store.list('merchant_order').length, 0); store.close(); });
test('live mode, amount/currency/payee/mandate/reference mismatches cannot enter pending queue', () => { const { store, run } = setup(); const cases = [ { livemode: true }, { amount: 1 }, { currency: 'usd' }, { metadata: { payee_id: 'attacker' } }, { metadata: { mandate_hash: 'wrong' } } ]; for (const patch of cases) { const e = event(run); const o = e.data.object as unknown as { metadata: Record<string, string> }; Object.assign(o, { ...patch, ...('metadata' in patch ? { metadata: { ...o.metadata, ...patch.metadata } } : {}) }); assert.throws(() => queueVerifiedStripeEvent(store, e)); } const live = event(run); live.livemode = true; assert.throws(() => queueVerifiedStripeEvent(store, live)); const noApproval = store.get<Run>('run', run.id)!; noApproval.approval = undefined; store.put('run', run.id, noApproval); assert.throws(() => queueVerifiedStripeEvent(store, event(run))); assert.equal(store.list('stripe_webhook').length, 0); store.close(); });
test('polling and event workers share one lease and gate; only one capture and merchant order', async t => { const p = provider(t); const { store, c, run } = setup(); queueVerifiedStripeEvent(store, event(run)); const other = new Commerce(store, 'stripe'); for (let i = 0; i < 5; i++) await Promise.all([c.processOne(), other.processOne()]); assert.equal(p.captures(), 1); assert.equal(c.get(run.id).status, 'CONFIRMED'); assert.equal(store.list('merchant_order').length, 1); assert.equal(store.get<WebhookReceipt>('stripe_webhook', 'evt_fixture')?.status, 'HANDLED'); assert.equal(store.get<WebhookReceipt>('stripe_webhook', 'evt_fixture')?.retrievedState, 'requires_capture'); store.close(); });
test('notification cannot bypass a revoked quote between authorization and capture', async t => { const p = provider(t); const { store, c, run } = setup(); queueVerifiedStripeEvent(store, event(run)); c.demoControl(run.id, 'buyer', 'revoke_quote'); for (let i = 0; i < 4; i++) await c.processOne(); assert.equal(c.get(run.id).paymentState, 'CANCELED'); assert.equal(p.captures(), 0); assert.equal(store.list('merchant_order').length, 0); store.close(); });
test('late/reordered requires_capture event on settled run retrieves succeeded and never regresses or recaptures', async t => { const p = provider(t); const { store, c, run } = setup(); for (let i = 0; i < 4; i++) await c.processOne(); const settled = c.get(run.id); const count = p.captures(); queueVerifiedStripeEvent(store, event(settled, 'evt_late_fixture')); await c.processOne(); assert.equal(c.get(run.id).status, 'CONFIRMED'); assert.equal(c.get(run.id).paymentId, settled.paymentId); assert.equal(p.captures(), count); assert.equal(store.get<WebhookReceipt>('stripe_webhook', 'evt_late_fixture')?.retrievedState, 'succeeded'); assert.equal(store.list('merchant_order').length, 1); store.close(); });
test('pending receipt survives database close/reopen; event arriving before job finish is not deleted', async t => { provider(t); const folder = mkdtempSync(join(tmpdir(), 'crosscart-webhook-')); const file = join(folder, 'pending.sqlite'); t.after(() => rmSync(folder, { recursive: true, force: true })); const { store, run } = setup(new Store(file)); const claim = store.claim()!; queueVerifiedStripeEvent(store, event(run)); store.finish(run.id, claim.token, true); assert.equal(store.db.prepare('SELECT COUNT(*) n FROM jobs').get()!.n, 1); store.close(); const reopened = new Store(file); const c = new Commerce(reopened, 'stripe'); assert.equal(reopened.pendingWebhooks(run.id).length, 1); for (let i = 0; i < 4; i++) await c.processOne(); assert.equal(c.get(run.id).status, 'CONFIRMED'); assert.equal(reopened.pendingWebhooks(run.id).length, 0); reopened.close(); });
test('unknown same-operation retrieval stays pending, retries without new capture, terminal network failure preserves settlement', async t => { provider(t); const { store, c, run } = setup(); for (let i = 0; i < 4; i++) await c.processOne(); queueVerifiedStripeEvent(store, event(c.get(run.id), 'evt_unavailable_fixture')); t.mock.method(StripePaymentProvider.prototype, 'retrieve', async () => { throw new OperationUnknown(); }); for (let i = 0; i < 8; i++) { store.db.prepare('UPDATE jobs SET due_at=0').run(); await c.processOne(); } assert.equal(c.get(run.id).status, 'CONFIRMED'); assert.equal(store.get<WebhookReceipt>('stripe_webhook', 'evt_unavailable_fixture')?.status, 'REJECTED'); assert.equal(store.get<WebhookReceipt>('stripe_webhook', 'evt_unavailable_fixture')?.attempts, 8); assert.equal(store.list('merchant_order').length, 1); store.close(); });
test('lease covers extra receipt lookups; expired lease recovery rejects completion from the old worker token', t => { const store = new Store(':memory:'); t.mock.timers.enable({ apis: ['Date'], now: 1000000 }); store.enqueue('lease_fixture'); const first = store.claim()!; t.mock.timers.tick(65000); assert.equal(store.claim(), undefined); t.mock.timers.tick(26000); const recovered = store.claim()!; assert.notEqual(recovered.token, first.token); store.finish(first.id, first.token, true); assert.equal(store.db.prepare('SELECT token FROM jobs WHERE run_id=?').get(first.id)!.token, recovered.token); store.finish(recovered.id, recovered.token, true); assert.equal(store.db.prepare('SELECT COUNT(*) n FROM jobs').get()!.n, 0); store.close(); });
