'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRightIcon, CheckCircleIcon, XCircleIcon, SpinnerGapIcon } from '@phosphor-icons/react/ssr';
import { ConsentArt } from './consent-art';
import { ThemeSwitch } from './theme-switch';
import type { Offer, Run, Scenario } from '../lib/types';
import type { ShoppingRecord } from '../lib/shopping';
type Compared = Offer & { failures: string[] };
type Session = { owner: string; provider: 'local' | 'stripe'; ai: string };
const money = (n: number) => new Intl.NumberFormat('en-HK', { style: 'currency', currency: 'HKD', maximumFractionDigits: n % 100 ? 2 : 0 }).format(n / 100);
const scenarios: [Scenario, string][] = [['happy', 'Normal purchase'], ['price_drift', 'Price changes +HK$100'], ['order_failure', 'Captured → order fails'], ['capture_timeout', 'Capture response lost'], ['order_timeout', 'Order response lost'], ['refund_pending', 'Refund stays pending'], ['refund_failed', 'Refund needs attention']];
async function api<T>(path: string, body?: unknown): Promise<T> {
  const response = await fetch(`/api/${path}`, body === undefined ? { cache: 'no-store' } : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Request unavailable'); return result;
}
function defaultDate() { const date = new Date(Date.now() + 2 * 86400000); return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Hong_Kong', year: 'numeric', month: '2-digit', day: '2-digit' }).format(date); }
export default function Home() {
  const [session, setSession] = useState<Session>(); const [account, setAccount] = useState('demo-buyer'); const [password, setPassword] = useState('crosscart-demo');
  const [run, setRun] = useState<Run>(); const [offers, setOffers] = useState<Compared[]>([]); const [recent, setRecent] = useState<Run[]>([]);
  const [text, setText] = useState('幫我搵 HK$1,800 以下嘅耳機，要官方保養，兩日內收到。'); const [budget, setBudget] = useState('1800'); const [deadline, setDeadline] = useState(defaultDate);
  const [shopping, setShopping] = useState<ShoppingRecord>(); const [revisionBase, setRevisionBase] = useState<{ shoppingId: string; runId: string }>();
  const [category, setCategory] = useState('headphones'); const [warrantyChoice, setWarrantyChoice] = useState('true');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (id: string) => {
    const r = await api<Run>(`runs/${id}`); setRun(r);
    if (r.shoppingId) setShopping(await api<ShoppingRecord>(`shopping/${r.shoppingId}`)); else setShopping(undefined);
    if (!r.mandate) setOffers(await api<Compared[]>(`runs/${id}/offers`));
    setRecent(await api<Run[]>('runs'));
  }, []);
  useEffect(() => {
    let active = true;
    void api<Session>('session').then(async s => { if (!active) return; setSession(s); setRecent(await api<Run[]>('runs')); const id = new URLSearchParams(window.location.search).get('run'); if (id) await load(id); }).catch(() => {});
    return () => { active = false; };
  }, [load]);
  const watchedId = run?.id, watchedStatus = run?.status;
  useEffect(() => {
    if (!watchedId || !watchedStatus || !['PROCESSING', 'WAITING_PAYMENT', 'RECOVERING'].includes(watchedStatus)) return;
    const timer = setInterval(() => { void load(watchedId).catch(e => setError(e.message)); }, 650);
    return () => clearInterval(timer);
  }, [watchedId, watchedStatus, load]);
  async function perform(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Request unavailable'); } finally { setBusy(false); } }
  function navigate(id?: string) { window.history.replaceState(null, '', id ? `/?run=${id}` : '/'); }
  const stage = !run ? 0 : !run.mandate ? 1 : ['QUOTED', 'APPROVED'].includes(run.status) ? 2 : ['PROCESSING', 'WAITING_PAYMENT'].includes(run.status) ? 3 : 4;
  const mode = run?.providerMode || session?.provider || 'local';
  const primaryOffer = offers.find(o => !o.failures.length && o.merchantId === run?.intent.rankedMerchantIds?.[0]) || offers.find(o => !o.failures.length);
  function revise() { if (!run?.shoppingId) return; setRevisionBase({ shoppingId: run.shoppingId, runId: run.id }); setRun(undefined); setShopping(undefined); setText(''); navigate(); }
  async function choose(merchantId: string) { if (!run) return; setRun(await api<Run>(`runs/${run.id}/quote`, { merchantId })); }
  const previousStage = useRef(stage);
  useEffect(() => {
    if (previousStage.current === stage) return;
    previousStage.current = stage;
    const heading = document.querySelector<HTMLElement>('#purchase-workspace h2');
    heading?.focus({ preventScroll: true });
    if (heading && (heading.getBoundingClientRect().top < 0 || heading.getBoundingClientRect().top > window.innerHeight * .7)) heading.scrollIntoView({ block: 'start', behavior: 'auto' });
  }, [stage]);
  useEffect(() => {
    if (!error) return;
    document.getElementById('request-error')?.scrollIntoView({ block: 'nearest', behavior: 'auto' });
  }, [error]);
  return <div className={`app-shell ${session ? 'is-authenticated' : 'is-login'}`}><a className="skip-link" href="#purchase-workspace">Skip to purchase</a>
    <header className="topbar"><Link className="brand" href="/" aria-label="CrossCart home"><Image src="/icon.svg" width={44} height={44} alt="" className="brand-mark"/>CrossCart</Link><nav className="steps" aria-label="Purchase steps">{['Intent', 'Compare', 'Approve', 'Progress', 'Result'].map((s, i) => <div key={s} aria-current={session && stage === i ? 'step' : undefined} className={session && stage === i ? 'active' : session && stage > i ? 'complete' : ''}><span aria-hidden="true"/>{s}</div>)}</nav><p className="top-tagline">AI shopping, on your terms.</p></header>
    <main>
      <div className="main-flow">
      <div className="intro"><h1>Let AI compare.<br/><em>Keep the final say.</em></h1><p className="intro-copy">AI compares. You approve the exact deal.<br/>Payment and refund stay traceable.</p></div>
      <ConsentArt showDemoQuote={stage === 1 && primaryOffer?.merchantName === 'Merchant A' && primaryOffer.totalMinor === 174900}/>
      {!session ? <section className="login surface" id="purchase-workspace" aria-busy={busy}><p className="eyebrow">TEST DEMO ACCESS</p><h2 tabIndex={-1}>Enter the working demo</h2><p>Account access only. No government eID or verified legal identity.</p><form onSubmit={e => { e.preventDefault(); void perform(async () => { await api('login', { account, password }); setSession(await api<Session>('session')); setRecent(await api<Run[]>('runs')); }); }}><label>Demo account<select value={account} onChange={e => setAccount(e.target.value)}><option value="demo-buyer">Demo buyer</option><option value="demo-other">Other buyer (ownership test)</option></select></label><label>Demo password<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label><button disabled={busy}>{busy ? 'Signing in…' : 'Enter demo'}</button></form><small>Demo password: crosscart-demo</small></section> : <>
        <div className="workspace"><section className={`content surface stage-${stage}`} id="purchase-workspace" key={`${stage}:${run?.status || 'intent'}`} aria-live="polite" aria-busy={busy}>{error && <div className="error" id="request-error" role="alert">{error}</div>}
          {stage === 0 && <><p className="eyebrow">01 / SHOPPING INTENT{revisionBase ? ' · NEW VERSION' : ''}</p><h2 tabIndex={-1}>What are you looking for?</h2><p className="muted">Describe your requirements, then review the interpretation before comparing.</p>{revisionBase && <p className="parser-note">This creates a new search. Your previous purchase, mandate and payment stay on their own record.</p>}<form onSubmit={e => { e.preventDefault(); void perform(async () => {
            if (!shopping) {
              const draft = await api<ShoppingRecord>('shopping', { text, parentShoppingId: revisionBase?.shoppingId, parentRunId: revisionBase?.runId }); setShopping(draft); setBudget(draft.proposal.budgetMinor == null ? '' : String(draft.proposal.budgetMinor / 100)); setDeadline(draft.proposal.deliveryBefore || ''); setCategory(draft.proposal.category === 'unknown' ? '' : 'headphones'); setWarrantyChoice(draft.proposal.officialWarranty == null ? '' : String(draft.proposal.officialWarranty));
            } else {
              const minor = Math.round(Number(budget) * 100); const confirmed = await api<ShoppingRecord>(`shopping/${shopping.id}/confirm`, { category, currency: 'hkd', budgetMinor: minor, officialWarranty: warrantyChoice === 'true', deliveryBefore: deadline }); setShopping(confirmed);
              const r = await api<Run>('runs', { shoppingId: confirmed.id, text, budgetMinor: minor, officialWarranty: warrantyChoice === 'true', deliveryBefore: deadline }); navigate(r.id); await load(r.id); setRevisionBase(undefined);
            }
          }); }}><label>Your request<textarea value={text} onChange={e => { setText(e.target.value); setShopping(undefined); }} rows={3} required maxLength={2000}/></label>
            {shopping && <div className="interpretation"><p className="mode-tag">{shopping.parseMode === 'live-ai' ? 'LIVE AI INTERPRETATION' : 'DETERMINISTIC FALLBACK'} · VERSION {shopping.version}</p><p className="fine-print">{shopping.model || 'No model configured'} · Hong Kong date {shopping.clock.date} · {shopping.latencyMs} ms{shopping.fallbackReason ? ` · ${shopping.fallbackReason}` : ''}</p><p className="fine-print">Preference priority: {shopping.proposal.softPreferences.join(' → ') || 'Compare total price after hard constraints'}</p>{shopping.proposal.unresolvedQuestions.length > 0 && <div className="questions"><strong>Please confirm these points</strong><ul>{shopping.proposal.unresolvedQuestions.map(q => <li key={q}>{q}</li>)}</ul></div>}
              <div className="form-grid"><label>Product<select required value={category} onChange={e => setCategory(e.target.value)}><option value="">Confirm product</option><option value="headphones">Demo headphones</option></select></label><label>Currency<input value="HKD" readOnly /></label><label>Total budget · HKD<input type="number" min="1" max="100000" step="0.01" value={budget} onChange={e => setBudget(e.target.value)} required /></label><label>Arrive by<input type="date" value={deadline} onChange={e => setDeadline(e.target.value)} required /></label></div><label>Warranty requirement<select required value={warrantyChoice} onChange={e => setWarrantyChoice(e.target.value)}><option value="">Please confirm</option><option value="true">Official warranty (demo terms)</option><option value="false">Third-party warranty</option></select></label><p className="fine-print">Confirming these fields resolves the questions above. Unknown stock, authenticity and feature claims remain unverified. A shopping budget does not authorize payment.</p>
            </div>}
            <button disabled={busy}>{busy ? 'Checking requirements…' : shopping ? 'Compare demo merchants →' : 'Understand request →'}</button></form><p className="fine-print">{session.ai === 'deterministic' ? 'No live AI configured; fallback is labeled.' : 'Live AI available. The actual mode and grounded sources appear after each request.'}</p></>}
          {stage === 1 && run && <>
            <div className="request-strip"><Image src="/crosscart-headphones.webp" width={64} height={64} alt="Concept image of the demo headphones"/><div><p>Headphones <span>·</span> Budget {money(run.intent.budgetMinor)} <span>·</span> {run.intent.officialWarranty ? 'Official warranty' : 'Third-party warranty okay'} <span>·</span> Arrive by {shortDate(run.intent.deliveryBefore)}</p><small>Demo Wireless Headphones, graphite</small></div><button className="text-button" disabled={busy} onClick={revise}>Edit</button></div>
            <h2 className="comparison-title" tabIndex={-1}>One product. All the details.</h2>
            <div className="comparison-columns" aria-hidden="true"><span>MERCHANT & DETAILS</span><span>TOTAL (HKD)</span><span>DELIVERY & ELIGIBILITY</span></div>
            <div className="offer-list">{offers.map(o => <article className={`offer ${o.failures.length ? 'ineligible' : 'eligible'} ${primaryOffer?.merchantId === o.merchantId ? 'recommended' : ''}`} key={o.merchantId}>
              <div className="merchant-details"><div className="merchant-name"><h3>{o.merchantName}</h3>{primaryOffer?.merchantId === o.merchantId && <span className="recommendation-label">Recommended</span>}</div><p>{o.warranty === 'official' ? 'Official warranty (demo terms)' : 'Third-party warranty'}</p><small>Item {money(o.subtotalMinor)} <span>+</span> Delivery {money(o.shippingMinor)}</small></div>
              <strong className="offer-price">{money(o.totalMinor)}</strong>
              <div className="offer-eligibility"><p>{fullDate(o.deliveryDate)}</p>{o.failures.length ? <><button className="ineligible-choice" aria-label={`Choose ${o.merchantName}`} disabled><XCircleIcon size={19} weight="fill" aria-hidden="true"/>Ineligible</button><small>{o.failures.join(' · ')}</small></> : <><span className="status-note"><CheckCircleIcon size={19} weight="fill" aria-hidden="true"/>Meets your requirements</span>{primaryOffer?.merchantId !== o.merchantId && <button className="text-button merchant-choice" disabled={busy} onClick={() => void perform(() => choose(o.merchantId))}>Choose {o.merchantName}</button>}</>}</div>
            </article>)}</div>
            {primaryOffer ? <div className="comparison-actions"><button disabled={busy} onClick={() => void perform(() => choose(primaryOffer.merchantId))}>Choose {primaryOffer.merchantName}<ArrowRightIcon size={23} aria-hidden="true"/></button><button className="text-button" disabled={busy} onClick={revise}>Revise request</button></div> : <p role="alert">No offer meets all constraints. Start a new search and adjust your requirements.</p>}
            <details className="comparison-explanation"><summary>Why this recommendation?</summary><div className="parser-note"><strong>{shopping?.comparisonMode === 'live-ai' ? 'Live AI comparison' : run.intent.parser === 'live-ai' ? 'Live AI explanation' : 'Deterministic fallback'}</strong><p>{run.intent.explanation}</p>{shopping && <><p className="fine-print">Interpretation: {shopping.parseMode} · ranking: {shopping.comparisonMode} · {shopping.model} · v{shopping.version}. Merchant facts below are synthetic adapter records.</p><details className="fact-evidence"><summary>View grounded comparison sources</summary><ul className="fact-refs">{shopping.comparison?.facts.map((f, i) => <li key={i}><code>{f.offerId}</code> · {f.field}: {f.field === 'totalMinor' ? money(Number(f.value)) : f.value}</li>)}</ul></details><p className="fine-print">Stock and independent authenticity verification: unknown.</p></>}</div></details>
          </>}
          {stage === 2 && run?.mandate && <><p className="eyebrow">03 / EXACT PURCHASE APPROVAL</p><h2 tabIndex={-1}>{run.status === 'APPROVED' ? 'This exact purchase is approved.' : 'Review what you are approving.'}</h2><div className="purchase-summary"><span className="tiny-label">DEMO DATA · {run.mandate.offer.merchantName}</span><h3>{run.mandate.offer.productName}</h3><p>{run.mandate.offer.variant} · quantity {run.mandate.offer.quantity}</p><strong className="total">{money(run.mandate.offer.totalMinor)}</strong><span>Exact total, including {money(run.mandate.offer.shippingMinor)} delivery</span></div><dl className="review-list"><div><dt>Seller</dt><dd>{run.mandate.offer.sellerId}</dd></div><div><dt>Actual test payee</dt><dd>{run.mandate.offer.payee}</dd></div><div><dt>Warranty / delivery</dt><dd>{run.mandate.offer.warranty} · {run.mandate.offer.deliveryDate}</dd></div><div><dt>Accepted merchant quote</dt><dd>{run.merchantQuote?.state || 'UNKNOWN'} · valid until {run.merchantQuote?.validUntil || 'unknown'}</dd></div><div><dt>Approval expires</dt><dd>{new Date(run.mandate.expiresAt).toLocaleString('en-HK', { timeZone: 'Asia/Hong_Kong' })} HKT</dd></div></dl><p className="fine-print">Your {money(run.intent.budgetMinor)} search budget does not permit a different amount. A changed seller, product, total or term requires fresh consent.</p>{run.status === 'QUOTED' ? <button disabled={busy} onClick={() => void perform(async () => { setRun(await api<Run>(`runs/${run.id}/approve`, { mandateId: run.mandate!.id, hash: run.mandate!.hash })); })}>Approve exact {money(run.mandate.offer.totalMinor)} purchase</button> : <div className="actions"><button disabled={busy} onClick={() => void perform(async () => { setRun(await api<Run>(`runs/${run.id}/commit`, {})); })}>{mode === 'local' ? 'Execute approved local test purchase →' : 'Continue to Stripe test authorization →'}</button><button className="secondary" disabled={busy} onClick={() => void perform(async () => { setRun(await api<Run>(`runs/${run.id}/revoke`, {})); })}>Revoke approval</button></div>}</>}
          {stage === 3 && run && <><p className="eyebrow">04 / TRANSACTION PROGRESS</p><h2 tabIndex={-1}>{run.recoveryState === 'RECONCILING' ? 'Checking the same transaction.' : run.status === 'WAITING_PAYMENT' ? 'Authorize the exact card payment.' : 'Completing your approved purchase.'}</h2><p className="muted">{run.recoveryState === 'RECONCILING' ? 'The response was lost. We retrieve the same operation before continuing. No second charge is created.' : 'Payment and merchant order are verified separately. This is not a purchase success message.'}</p><div className="transaction-progress" role="status"><SpinnerGapIcon size={26} aria-hidden="true"/><span>Checking transaction state</span></div>{run.checkoutUrl && run.status === 'WAITING_PAYMENT' && <a className="button" href={run.checkoutUrl}>Open Stripe hosted test checkout →</a>}<StateCards run={run}/>{run.demoCaptureHold && <p className="questions">Demo capture paused. Authorization is not a charge; resume or withdraw the quote using the demo controls.</p>}</>}
          {stage === 4 && run && <><p className="eyebrow">05 / RESULT & RECOVERY</p><h2 tabIndex={-1}>{run.status === 'CONFIRMED' ? 'Purchase confirmed.' : run.status === 'BLOCKED' ? 'Purchase blocked.' : run.status === 'RECOVERED' ? 'Order failed. Refund confirmed.' : run.status === 'NEEDS_OPERATOR' ? 'This needs attention.' : 'Order failed. Recovery in progress.'}</h2><p className="muted">{run.reason}</p>{run.status === 'BLOCKED' && run.currentOffer && run.mandate && <div className="drift"><div><span>Approved</span><strong>{money(run.mandate.offer.totalMinor)}</strong></div><div><span>Current</span><strong>{money(run.currentOffer.totalMinor)}</strong></div><div><span>Difference</span><strong>+{money(run.currentOffer.totalMinor - run.mandate.offer.totalMinor)}</strong></div><p><strong>Payment: {run.paymentState === 'NOT_STARTED' ? 'NOT EXECUTED' : run.paymentState}</strong><br/>Fresh approval required. Your original mandate remains unchanged.</p></div>}<StateCards run={run}/><p className="next-action">{run.status === 'CONFIRMED' ? 'Your exact payment and demo order are both confirmed. No real goods will be delivered.' : run.status === 'BLOCKED' ? 'Start a fresh purchase to review and approve the new conditions.' : run.recoveryState === 'REFUNDED' ? `${mode === 'local' ? 'LOCAL TEST refund completed.' : 'Provider refund succeeded; this does not prove bank posting.'} The order was not completed.` : run.recoveryState === 'PENDING' ? 'Refund is pending. Refresh safely; do not pay again.' : 'Keep this reference. Operator/provider reconciliation is required; do not pay again.'}</p><button className="secondary" onClick={() => { setRun(undefined); setShopping(undefined); setRevisionBase(undefined); navigate(); }}>Start a fresh purchase</button></>}
        </section></div>
      </> }
      </div>
      {session && <aside className="toolbox" aria-label="Purchase tools and evidence">
          {run?.shoppingId && <section className="revision-note"><h3>Revise your requirements</h3><p>Start a new version. Existing consent and transactions remain traceable.</p><button className="secondary small" disabled={busy} onClick={revise}>Revise in a new version</button></section>}
          {run && <details className="demo-controls" open><summary>Demo scenario controls</summary><p>{mode === 'stripe' ? 'Controlled merchant faults; payment and refund results are retrieved from Stripe test mode.' : 'Controlled faults in the local payment and demo merchant adapters.'}</p><label>Scenario<select aria-label="Demo scenario" value={run.scenario} disabled={busy || !['COMPARING', 'QUOTED', 'APPROVED'].includes(run.status)} onChange={e => void perform(async () => { setRun(await api<Run>(`runs/${run.id}/scenario`, { scenario: e.target.value })); })}>{scenarios.filter(([value]) => mode === 'local' || !['capture_timeout', 'refund_pending', 'refund_failed'].includes(value)).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{run.mandate && <><p className="fine-print">Accepted quote: {run.merchantQuote?.state || 'UNKNOWN'} · capture: manual. Catalogue updates preserve the accepted quote; withdrawal invalidates it.</p><div className="demo-action-grid">{(['hold_capture', 'resume_capture', 'revoke_quote', 'catalogue_update'] as const).map((action, i) => <button key={action} className="secondary small" disabled={busy || !['QUOTED', 'APPROVED', 'PROCESSING', 'WAITING_PAYMENT'].includes(run.status) || ['CAPTURING', 'CAPTURED'].includes(run.paymentState)} onClick={() => void perform(async () => { setRun(await api<Run>(`runs/${run.id}/demo-control`, { action })); })}>{['Pause capture', 'Resume capture', 'Withdraw quote', 'Update catalogue only'][i]}</button>)}</div></>}</details>}
          {run && <details className="evidence"><summary>Judge evidence</summary><p className="tiny-label">{mode === 'local' ? 'LOCAL TEST OBJECTS — NOT STRIPE' : 'STRIPE TEST OBJECTS'}</p><dl><div><dt>Shopping interpretation</dt><dd>{run.shoppingId || 'Legacy confirmed form'} · v{run.shoppingVersion || '—'}<br/>{shopping ? `${shopping.parseMode} / ${shopping.comparisonMode} · ${shopping.model}` : '—'}<br/>Previous run: {run.previousRunId || '—'}</dd></div><div><dt>Quote validity</dt><dd>{run.merchantQuote?.state || 'UNKNOWN'} · {run.merchantQuote?.validUntil || '—'}</dd></div><div><dt>Run</dt><dd>{run.id}</dd></div><div><dt>Mandate / version</dt><dd>{run.mandate?.id || '—'} / {run.mandate?.version || '—'}</dd></div><div><dt>Integrity identifier (not user signature)</dt><dd>{run.mandate?.hash || '—'}</dd></div><div><dt>Payment / provider state</dt><dd>{run.paymentId || run.sessionId || 'not created'}<br/>{run.providerState || run.paymentState}</dd></div><div><dt>Order</dt><dd>{run.orderId || 'not created'} / {run.orderState}</dd></div><div><dt>Refund</dt><dd>{run.refundId || 'not created'} / {run.refundState || '—'}</dd></div></dl>{!!run.webhookReceipts?.length && <div className="receipt-list"><strong>Verified webhook receipts</strong>{run.webhookReceipts.map(r => <p key={r.id}><code>{r.id}</code><br/>{r.eventType} · {r.status} · retrieved {r.retrievedState || 'pending'}</p>)}</div>}<ol className="audit">{run.events?.map(e => <li key={e.id}><time>{new Date(e.timestamp).toLocaleTimeString('en-HK', { timeZone: 'Asia/Hong_Kong' })}</time><span>{e.source}</span><p>{e.reason}</p><code>{e.previousState} → {e.newState}</code></li>)}</ol></details>}
          {recent.length > 0 && <details className="recent"><summary>Saved purchases · {recent.length}</summary>{recent.map(r => <button className="saved-run" key={r.id} onClick={() => void perform(async () => { navigate(r.id); await load(r.id); })}><span>{r.mandate?.offer.merchantName || 'Shopping request'}</span><small>{r.status} · {r.id.slice(0, 8)}</small></button>)}</details>}
        </aside>}
      {error && !session && <div className="error" id="request-error" role="alert">{error}</div>}
      <footer><div><strong>CrossCart</strong><span>{!session ? 'SHOPPING DEMO' : mode === 'local' ? 'LOCAL TEST ADAPTER' : 'STRIPE TEST MODE'} · DEMO MERCHANTS · HKD</span></div><div className="footer-tools"><Link href="/demo">Video &amp; pitch deck</Link><Link href="/evidence">Judge guide</Link><Link href="/benchmark">Manual comparison</Link><span>{new Intl.DateTimeFormat('en-HK', { timeZone: 'Asia/Hong_Kong', day: 'numeric', month: 'short', year: 'numeric' }).format(new Date())}</span><ThemeSwitch/></div></footer>
      <details className="demo-boundary"><summary>About this working demo</summary><p>{!session ? 'Sign in to see the configured payment adapter.' : mode === 'local' ? 'No real money moves. This purchase uses local simulated payment objects; it is not evidence of an official Stripe transaction.' : 'Official Stripe test-mode adapter selected. Demo merchants share a controlled test account; no real goods or third-party settlement.'} All merchant, product and warranty data are synthetic. Demo account access is not government eID or a verified legal identity.</p></details>
    </main>
  </div>;
}
function StateCards({ run }: { run: Run }) { return <div className="state-cards"><div><span>PAYMENT</span><strong data-testid="payment-state">{run.paymentState}</strong><small>{run.providerMode === 'local' ? 'Local test adapter' : 'Stripe test mode'}</small></div><div><span>MERCHANT ORDER</span><strong data-testid="order-state">{run.orderState}</strong><small>Demo merchant adapter</small></div><div><span>RECOVERY</span><strong data-testid="recovery-state">{run.recoveryState}</strong><small>{run.refundState ? `Refund provider: ${run.refundState}` : 'Independent of order success'}</small></div></div>; }

function shortDate(value: string) { return new Intl.DateTimeFormat('en-HK', { day: '2-digit', month: 'short', timeZone: 'Asia/Hong_Kong' }).format(new Date(`${value}T00:00:00+08:00`)); }
function fullDate(value: string) { return new Intl.DateTimeFormat('en-HK', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric', timeZone: 'Asia/Hong_Kong' }).format(new Date(`${value}T00:00:00+08:00`)); }
