import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { Store } from '../lib/store';
import { Shopping } from '../lib/shopping';
import { Commerce } from '../lib/service';
import { deliveryDefault } from '../lib/policy';
if (!process.env.AI_API_KEY || !process.env.AI_MODEL) throw new Error('Live model credentials required.');
const output = process.env.CROSSCART_EVIDENCE_DIR || 'output/evidence/2026-10-03-completion-audit'; mkdirSync(output, { recursive: true });
const store = new Store(':memory:'), shopping = new Shopping(store), commerce = new Commerce(store, 'local');
const fields = { category: 'headphones', currency: 'hkd', budgetMinor: 180000, officialWarranty: true, deliveryBefore: deliveryDefault() };
const initial = await shopping.draft('audit-buyer', 'HK$1800 以下耳機，要官方保養，兩日內收到，最平嘅。');
assert.equal(initial.parseMode, 'live-ai'); const a = await shopping.confirm(initial.id, 'audit-buyer', fields); assert.equal(a.comparisonMode, 'live-ai');
let previous = commerce.create('audit-buyer', initial.input, fields, a.confirmed, a); previous = commerce.quote(previous.id, 'audit-buyer', 'merchant_a'); previous = commerce.approve(previous.id, 'audit-buyer', previous.mandate!.id, previous.mandate!.hash);
const before = structuredClone(commerce.get(previous.id));
const draft = await shopping.draft('audit-buyer', '唔使官方保養，第三方都得，兩日內收到，揀最平。', a.id, previous.id);
writeFileSync(`${output}/live-warranty-draft.json`, JSON.stringify(draft, null, 2)); assert.equal(draft.parseMode, 'live-ai'); assert.equal(draft.proposal.officialWarranty, false); assert.equal(draft.proposal.budgetMinor, 180000);
const b = await shopping.confirm(draft.id, 'audit-buyer', { ...fields, officialWarranty: false }); writeFileSync(`${output}/live-warranty.json`, JSON.stringify({ checkedAt: new Date().toISOString(), scope: 'Actual model requests and read-only synthetic merchant tools; previous approval uses local persistence, no payment executed', previousSearch: a, revision: b, previousRun: { id: before.id, mandate: before.mandate, approval: before.approval }, cost: 'not_calculated' }, null, 2));
assert.equal(b.comparisonMode, 'live-ai'); assert.equal(b.comparison!.recommendation.rankedOfferIds[0], 'demo_offer_b_v1'); assert.deepEqual(commerce.get(previous.id), before); assert.equal(store.list('local_payment').length, 0);
console.log(`Actual model warranty follow-up passed: A -> B; version ${b.version}; old approval unchanged; no payment executed.`); store.close();
